version: '3.7'

services:
  accesslog:
    image: diamol/ch04-access-log

  iotd:
    image: diamol/ch04-image-of-the-day
    ports:
      - "80"

  image-gallery:
    image: diamol/ch04-image-gallery
    ports:
      - "8010:80"
    depends_on:
      - accesslog
      - iotd